/// Flutter icons Sheba
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///   - family:  Sheba
///      fonts:
///       - asset: fonts/Sheba.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Sheba {
  Sheba._();

  static const _kFontFam = 'Sheba';
  static const String? _kFontPkg = null;
  // ignore: constant_identifier_names
  static const IconData Add_to_Playlist = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backward = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Bookmark = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Calendar = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData CardVisa = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Chat = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Delete = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Discover = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Download = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Email = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fbsocial = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Filter = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forward = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData G_pay = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gif = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Google = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Heart = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Home = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dmsend = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData InfoSquare = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insta = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Library = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Location = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Lock = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Mobile_Money = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData NotAdd = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Notification = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Password = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Paypal = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Permission = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Phone = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Play = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Plus = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData PrivacyPolicy = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Profile = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ReUptoYourFollowers = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Search = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Send = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Send_2 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Setting = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData smile = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Star1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Ticket = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Unlock = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData Wallet = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData youtube = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
